/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DhikrRouteImport } from './routes/dhikr'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as QuranRouteImport } from './routes/quran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DhikrRoute = DhikrRouteImport.update({
  id: '/dhikr',
  path: '/dhikr',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dhikr': typeof DhikrRoute
  '/methodology': typeof MethodologyRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dhikr': typeof DhikrRoute
  '/methodology': typeof MethodologyRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dhikr': typeof DhikrRoute
  '/methodology': typeof MethodologyRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/dhikr' | '/methodology' | '/qibla' | '/quran'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/dhikr' | '/methodology' | '/qibla' | '/quran'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dhikr'
    | '/methodology'
    | '/qibla'
    | '/quran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DhikrRoute: typeof DhikrRoute
  MethodologyRoute: typeof MethodologyRoute
  QiblaRoute: typeof QiblaRoute
  QuranRoute: typeof QuranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhikr': {
      id: '/dhikr'
      path: '/dhikr'
      fullPath: '/dhikr'
      preLoaderRoute: typeof DhikrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DhikrRoute: DhikrRoute,
  MethodologyRoute: MethodologyRoute,
  QiblaRoute: QiblaRoute,
  QuranRoute: QuranRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
