/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DhikrRouteImport } from './routes/dhikr'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as QiblaRouteImport } from './routes/qibla'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DhikrRoute = DhikrRouteImport.update({
  id: '/dhikr',
  path: '/dhikr',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dhikr': typeof DhikrRoute
  '/methodology': typeof MethodologyRoute
  '/qibla': typeof QiblaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dhikr': typeof DhikrRoute
  '/methodology': typeof MethodologyRoute
  '/qibla': typeof QiblaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dhikr': typeof DhikrRoute
  '/methodology': typeof MethodologyRoute
  '/qibla': typeof QiblaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dhikr' | '/methodology' | '/qibla'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dhikr' | '/methodology' | '/qibla'
  id: '__root__' | '/' | '/dhikr' | '/methodology' | '/qibla'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DhikrRoute: typeof DhikrRoute
  MethodologyRoute: typeof MethodologyRoute
  QiblaRoute: typeof QiblaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhikr': {
      id: '/dhikr'
      path: '/dhikr'
      fullPath: '/dhikr'
      preLoaderRoute: typeof DhikrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DhikrRoute: DhikrRoute,
  MethodologyRoute: MethodologyRoute,
  QiblaRoute: QiblaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
